# Site settings
title: Gordon's Blog
header-img: img/home-bg.png
email: splscoupon@gmail.com
copyright_name: gd875
description: > # this means to ignore newlines until "baseurl:"
  A blog by Gordon
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  gd875
learn_profile: gd875
email_username: splscoupon@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
